# Generated by Django 2.1.1 on 2019-12-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20191206_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecutre_number',
            new_name='lecture_number',
        ),
    ]
