# Generated by Django 2.1.1 on 2019-11-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_reply_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
