# Generated by Django 2.1.1 on 2019-11-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_lecture_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='divided_class_name',
            new_name='lecutre_number',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='capacity',
        ),
        migrations.AddField(
            model_name='lecture',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='department',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='lecture',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='lecture',
            name='university',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
