# Generated by Django 2.1.1 on 2019-11-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191118_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
